### ISSUE TITLE
Extract rar files not working

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-rtorrentvpn#19] opened 2017-03-24 22:41 UTC
Does ruTorrent need rar/unrar binaries to extract? When I exec into the container, it doesn't seem to have any binaries for extraction like unrar/rar or 7zr. Could this be why my rar'd torrents fail to extract despite seemingly being correctly setup to do so?

**Comment by b3vis** [comment] 2017-09-09 16:24
I have a similar issue where the 'unpack' plugin is enabled but it seems to stop extracting after a few days or so. I am able to right click an item and manually click unpack which works. I can also see unrar is a working executable in the container.

I was going to look into adding a 'on complete' command to unrar manually but then saw this.

**Comment by binhex** [comment] 2017-10-09 09:55
added in unrar package, please give the latest image a whirl

**Comment by b3vis** [comment] 2017-10-09 11:54
Excellent I can see the merged pr, would you be so kind to have the build on the docker hub updated please?

**Comment by b3vis** [comment] 2017-10-11 07:12
I built the image manually instead of being lazy and recreated my container and the problem persists I'm afraid. I will do some testing to see if I can get any useful debug information for this issue.

**Comment by binhex** [comment] 2017-10-17 13:46
unrar support added, give the latest image a go and let me know

**Comment by b3vis** [comment] 2017-10-19 06:17
Automatic unrar is now working for me after the latest commit. I noticed that my externally mapped plugins folder has been removed but reading the commit I understand the reasoning. Is there any ability to add plugins myself? I like to use this theme on my ruTorrent

https://github.com/Phlooo/ruTorrent-MaterialDesign

I though I could map this from my host into the webapps/rutorrent/plugins folder but that feels like it’s not the solution but I’m not adverse to the idea.

Thank you for your amazing work binhex 👍

**Comment by binhex** [comment] 2017-10-19 14:11
The ability to add in user plugins has just been done, see here for details:-

https://forums.lime-technology.com/topic/46127-support-binhex-rtorrentvpn/?do=findComment&comment=597317

**Comment by akizzle** [comment] 2017-10-19 14:47
Themes work beautiful but I believe permissions need to be altered after importing them. I just killed my docker container and re-created it and it loaded fine.

**Closed** 2017-11-06 17:12 UTC

**Comment by enoch85** [comment] 2019-01-01 18:44
I'm using Flood and have the same issue.

**Steps to reproduce**

(Everything here is done on the HOST, not the Docker image)

**1.** Create this script in `/mnt/PlexDownloads/media`t:
```
#!/bin/sh

if [ -d $1 ]; then
    find $1 -name '*.rar' -execdir unrar e -o- {} \; 
fi
```
**2.** `chown 1001:1001 /mnt/PlexDownloads/media/rtunrar.sh`

**3.** Add the following in `rtorrent.rc`:
```
# gets the full path of data of a torrent (it's a workaround for the possibly empty 'd.base_path' attribute)
method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"

# Extract when finsihed
method.set_key = event.download.finished,"execute=/mnt/PlexDownloads/media/rtunrar.sh,$d.get_base_path=,$d.get_name="
```

I've tested various combinations of the `methid.insert` command but nothing seems to work. Am I doing something wrong, or is it a bug? 

Thanks! cc @binhex
